# Generated by Django 5.1.2 on 2024-10-25 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="rascadores",
            fields=[
                (
                    "rascador_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_rascador", models.CharField(max_length=64, unique=True)),
                ("descipcion_rascador", models.TextField(blank=True)),
                ("image_url_rascador", models.URLField()),
                ("slug_rascador", models.SlugField(max_length=75, unique=True)),
                ("is_private", models.BooleanField()),
            ],
        ),
    ]
