# Generated by Django 5.1.2 on 2024-10-25 21:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_descipcion_rascador_rascadores_descripcion_rascador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_contacto', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('nombre_cliente', models.CharField(max_length=64)),
            ],
        ),
    ]
