# Generated by Django 5.1.2 on 2024-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contactforms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactforms',
            name='mail_cliente',
            field=models.EmailField(default=str, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactforms',
            name='mensaje',
            field=models.TextField(default=str),
            preserve_default=False,
        ),
    ]
